eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost1:8761/eureka/,http://localhost2:8769/eureka/
server:
  port: 8888
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign

