
#添加自定义外部目录并覆盖默认
spring:
    mvc:
        static-path-pattern: /**
    resources:
        static-locations: classpath:/tpl/admin/static/,classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
    thymeleaf:
        prefix: classpath:/tpl/admin/templates/
#指定message
    messages:
        #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
        basename: i18n/messages
        #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
        encoding: UTF-8
        cache-duration: -1

#数据源配置
    datasource:
        url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        #useGlobalDataSourceStat: true
    jpa:
        show-sql: true
        properties:
            hibernate:
              hbm2ddl:
                auto: create
