
#环境变量
spring:
   debug: true
    profiles:
       active: dev
    application:
       name: nfs
    thymeleaf:
       encoding: UTF-8
       cache: false
       mode: LEGACYHTML
    messages:
        #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
       basename: i18n/messages
        #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
       encoding: UTF-8
       cache-duration: -1
server:
    port: 7070
    servlet:
      context-path: /
    tomcat:
      uri-encoding: UTF-8

