#配置日志
logging:
#  config: classpath:config/log4j2.xml
  path: D:\log
  level:
    cn.lmz: debug #不同目录下的日志可配置不同级别
    org.springfromework: debug
    org.hibernate: error

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost1:8761/eureka/,http://localhost2:8769/eureka/
server:
  port: 9999

spring:
  application:
    name: oauth2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system?serverTimezone=GMT
    username: root
    password: root
    initialSize: 10
    maxActive: 100
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
security:
  filter-order: 0
