eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost1:8761/eureka/,http://localhost2:8769/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi
feign:
  hystrix:
    enabled: true