server:
  port: 8761
eureka:
  instance:
    hostname: localhost1
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost1:8761/eureka/,http://localhost2:8769/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/