server:
  port: 9012

eureka:
  instance:
    hostname: mk-eureka2
  client:
    register-with-eureka: true # 注册到eureka
    fetch-registry: true # 获取注册信息
    service-url:
      defaultZone: http://mk-eureka1:9011/eureka