server:
  port: 9010
  servlet:
    context-path:
spring:
  application:
    name: mk-eureka

eureka:
  instance:
    hostname: mk-eureka
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  server:
    enable-self-preservation: false # 关闭注册中心的保护机制
    eviction-interval-timer-in-ms: 5000 # 60000 # 清理时间间隔
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: false # 注册到eureka
    fetch-registry: false # 获取注册信息
    service-url:
      defaultZone: http:/localhost:9010/eureka

###actuator监控点 start####
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health
  endpoint:
      health:
        show-details: always
###actuator监控点 end####